### ISSUE TITLE
.pspg_conf file format - FYI for users

### ISSUE THREAD

**Issue by mahiki** [okbob/pspg#239]
*Please close this issue, this is only meant as a reference resource and I'm too lazy to make a PR adjusting the docs.*

### `PSPG_CONF` file syntax
I puzzled over this for a long time, then noticed the excellent menu item `Save setup`, which helped me understand the syntax for the .conf file.

Know that you are not using the `PSPG` syntax, here is how my current conf was saved, notice it is a TOML style with parameters not the same as the CLI flags.

```toml
ascii_menu = false
bold_labels = false
bold_cursor = false
ignore_case = false
ignore_lower_case = false
no_cursor = false
no_sound = false
no_mouse = false
less_status_bar = false
no_highlight_search = false
no_highlight_lines = false
force_uniborder = false
show_rownum = false
without_commandbar = false
without_topbar = false
vertical_cursor = false
on_sigint_exit = false
no_sigint_search_reset = false
double_header = false
quit_on_f3 = false
pgcli_fix = false
xterm_mouse_mode = true
show_scrollbar = true
menu_always = false
empty_string_is_null = true
last_row_search = true
progressive_load_mode = true
highlight_odd_rec = false
hide_header_line = false
on_exit_reset = false
on_exit_clean = false
on_exit_erase_line = false
on_exit_sgr0 = false
direct_color = false
theme = 16
border_type = 2
default_clipboard_format = 0
clipboard_app = 0
hist_size = 500
esc_delay = -1
```

I absolutely love this tool, use it every day a lot. I hope this helps someone!
